using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace POS.Domain.Common
{
   public class SetupClass
    {
        public string Store_ID { get; set; }
        public string Company_Info_1 { get; set; }
        public string Company_Info_2 { get; set; }
        public string Company_Info_3 { get; set; }
        public string Company_Info_4 { get; set; }
        public string Company_Info_5 { get; set; }
        public string Admin_Pass { get; set; }
        public string Non_Inv_Cost_Perc { get; set; }
        public int Use_Cost_Perc { get; set; }
        public string Invoice_Notes_1 { get; set; }
        public string Invoice_Notes_2 { get; set; }
        public string Invoice_Notes_3 { get; set; }
        public string Invoice_Notes_4 { get; set; }
        public string Invoice_Notes_5 { get; set; }
        public string Invoice_Notes_6 { get; set; }
        public string Invoice_Notes_7 { get; set; }
        public string Invoice_Notes_8 { get; set; }
        public string Invoice_Notes_9 { get; set; }
        public string Invoice_Notes_10 { get; set; }
        public int CCTip { get; set; }
        public int Auto_Tip_Size { get; set; }
        public string Auto_Tip_Perc { get; set; }
        public int Auto_Tip_Enabled { get; set; }
        public int Print_Kit_Items { get; set; }
        public int Print_Mod_Items { get; set; }
        public int CheckValidation { get; set; }
        public int Line_Combine { get; set; }
        public int PO_Print_Barcodes { get; set; }
        public string InetEMail { get; set; }
        public int Receipt_Equals { get; set; }
        public int Average_Cost { get; set; }
        public int DPT { get; set; }
        public int Use_Max_Balance { get; set; }
        public int Print_Acct_Balance { get; set; }
        public int Print_Amt_Saved { get; set; }
        public int Last_Price_Lookup { get; set; }
        public int Logo_Type { get; set; }
        public string Logo_Loc { get; set; }
        public string Scale_Tear { get; set; }
        public int TS_Use_Decimal { get; set; }
        public int Round_Nearest_Nickel { get; set; }
        public int POOrder { get; set; }
        public int Use_Barcode_Scale { get; set; }
        public string CostMarkUpPerc { get; set; }
        public int Round_Invoice { get; set; }
        public string Tax_ID { get; set; }
        public string Store_Email { get; set; }
        public int Serial_Track_Incoming { get; set; }
        public int Rentals_Prompt_Days { get; set; }
        public string AcctNum { get; set; }
        public int Prevent_PO_Excess { get; set; }
        public int Track_PO_DelNum { get; set; }
        public int Serial_Allow_Duplicates { get; set; }
        public int Customer_Price_Lookup { get; set; }
        public int Num_Days_GC_Exp { get; set; }
        public int ID_Valid_Days { get; set; }
        public int Use_MixNMatch { get; set; }
        public int PromptRentSell { get; set; }
        public int Req_InvIn_Desc { get; set; }
        public int Rentals_Unique { get; set; }
        public int AutoPayARInv { get; set; }
        public int PrintARInvSig { get; set; }
        public int CO_Req_Tips { get; set; }
        public int CO_Close_OnHold { get; set; }
        public int Log_Returns { get; set; }
        public int Bonus_to_Dollars { get; set; }
        public int Deduct_Ingredients { get; set; }
        public int Kitchen_Info { get; set; }
        public int Receipt_CC_Notes { get; set; }
        public int Clockout_Receipt { get; set; }
        public int Combine_Checks { get; set; }
        public int Shift_CashTips_Disinclude_CashCount { get; set; }
        public int Profit_Center_Takeout { get; set; }
        public int Profit_Center_Delivery { get; set; }
        public int Profit_Center_OpenTabs { get; set; }
        public int Check_ID1_Age { get; set; }
        public int Check_ID2_Age { get; set; }
        public string Check_ID1_Msg { get; set; }
        public string Check_ID2_Msg { get; set; }
        public int Check_ID1_BDayPrompt { get; set; }
        public string OnTheFly_Def_Vendor { get; set; }
        public string OnTheFly_Def_Dept { get; set; }
        public string OnTheFly_Def_Desc { get; set; }
        public int Tax_On_Tips { get; set; }
        public int Pullbacks_Use_TimeClock { get; set; }
        public int OnTheFly_Def_Taxed { get; set; }
        public int OnTheFly_Def_Foodstamp { get; set; }
        public int OnTheFly_Prompt_Cost { get; set; }
        public string SecCurr_Exchange_Rate { get; set; }
        public string SecCurr_Desc { get; set; }
        public string SecCurr_Symbol { get; set; }
        public decimal CC_Floor_Amt { get; set; }
        public decimal Cash_Alert_Level { get; set; }
        public decimal Cash_Lockup_Level { get; set; }
        public int Tips_Deny_Settle { get; set; }
        public string Global_Transfer_Markup { get; set; }
        public int Use_Global_Transfer_Markup { get; set; }
        public int Tips_Keep_Check_Open { get; set; }
        public string Invoice_Notes_Top { get; set; }
        public int Print_Dept_Notes { get; set; }
        public string Store_Refund_Media { get; set; }
        public string Store_Credit_Notes { get; set; }
        public decimal Large_Purchase { get; set; }
        public decimal CheckDLFloor { get; set; }
        public decimal CheckPNFloor { get; set; }
        public int Ent_Add_Missing_Records { get; set; }
        public int Receipt_Combine_Lines { get; set; }
        public int Scale_Tare2 { get; set; }
        public int Layway_Type { get; set; }
        public int Layway_Deposit_Type { get; set; }
        public float Layway_Deposit_Minimum { get; set; }
        public int Layway_Cancellation_Days { get; set; }
        public int Layway_Pre_Cancellation_Type { get; set; }
        public float Layway_Pre_Cancellation_Fee { get; set; }
        public int Layway_Post_Cancellation_Type { get; set; }
        public float Layway_Post_Cancellation_Fee { get; set; }
        public int Layway_Allow_Partial_Pickup { get; set; }
        public int EnforceProperties { get; set; }
        public int ValidReturnWindow { get; set; }
        public int CashDrawerSelectionType { get; set; }
        public int WorkWeekStartDay { get; set; }
        public int LogExceptions { get; set; }
        public decimal CancelledCheckFee { get; set; }
        public int AddItemHideTS { get; set; }
        public int AllowStandaloneModifiers { get; set; }
        public decimal DefaultDrawerStart { get; set; }
        public int Use_Dept_Cost_Calculation { get; set; }
        public string Store_Description { get; set; }
        public int Square_Footage { get; set; }
        public int Population_Served { get; set; }
        public int DeliveryAssignmentOrder { get; set; }
        public int ReceiptCustInfo { get; set; }
        public int ArchiveData_NumDays { get; set; }
        public int LoginCheckExitPerm { get; set; }
        public int selectPizzaBy { get; set; }
        public string donationNotes { get; set; }
        public int printToppingsOnOneLine { get; set; }
        public string Invoice_Discounts_X_Level { get; set; }
        public int Drawer_OverShort_Recounts { get; set; }
        public int EBT_Exempt_Tax { get; set; }
        public int Shift_Assignment { get; set; }
        public int EOD_Allowance_TimeClock { get; set; }
        public int EOD_Allowance_OnHold { get; set; }
        public int EOD_Require_MoneyCount { get; set; }
        public string Drawer_Count_Threshhold_Recount { get; set; }
        public int NumStoreCreditReceipts { get; set; }
        public int LayawayForceDepositMinimum { get; set; }
        public int HideInvoiceQuantityTextbox { get; set; }
        public int HideInvoiceChangeQuantityButton { get; set; }
        public int ChargeForToppingSubstitutions { get; set; }
        public int ViewableReportHistory { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public int PrintDirections { get; set; }
        public int PrintDirectionsMethod { get; set; }
        public int PrintReturnDirections { get; set; }
        public int PrintCustomerInfoOnKitchenPrinter { get; set; }
        public string ParentTemplateID { get; set; }
        public int IsTemplate { get; set; }
        public string GC_Gateway_port { get; set; }
        public decimal MaxCashback { get; set; }
        public int SecurityMethod { get; set; }
        public int TaxRounding { get; set; }
        public int ForcedSelectionOrderingProcess { get; set; }
        public int LayawayEnabled { get; set; }
        public int CheaperToppingsFree { get; set; }
        public int LineDiscountPromptType { get; set; }
        public int Batch_Size { get; set; }
        public string EncryptionHash { get; set; }
        public decimal NoCreditCardSignatureBelow { get; set; }
        public decimal CreditCardPreAuthAmount { get; set; }
        public int PreAuthorizePrompt { get; set; }
        public int PreAuthorizeNewTabPrompt { get; set; }
        public int Loyalty_Plan_ID { get; set; }
        public int CustomerLoyaltyPrompt { get; set; }
        public int AutoCombo { get; set; }
        public int PrintPaidStatusInKitchenReceipt { get; set; }
        public int WhenRemovingADefaultTopping { get; set; }
        public int Perform_Batchsettlement_OnEndofDay { get; set; }
        public string StdInvPercentAllowed { get; set; }
        public int OvertimeCalculationMethod { get; set; }
        public int OrderPreparationTime { get; set; }
        public string Store_Declaration_Form { get; set; }
        public int ScaleBarcodeMethod { get; set; }
        public string ScaleBarcodeFormat { get; set; }
        public int ShowRestaurantScanTextbox { get; set; }
        public int PromptPayoutItemNum { get; set; }
        public string Personal_Check_Return_Notes { get; set; }
        public string Corporate_Check_Return_Notes { get; set; }
        public int UpdateItemVendorCostFromPO { get; set; }
        public string CCTipPercWithheld { get; set; }
        public int DeliveryDirectionsProvider { get; set; }
        public string AutoBatchSettlementStatus_EmailId { get; set; }
        public string AutoBatchSettlement_Time { get; set; }
        public int AutoBatchSettlementStatus { get; set; }
        public int SubtractDrawerStartFromDeposits { get; set; }
        public string StationProcessingMobileTransactions { get; set; }
        public int Round_Cash_Transactions { get; set; }
        public string Phone_1 { get; set; }
        public int Prompt_Distributor { get; set; }
        public string Prompt_OutOfDate { get; set; }
        public string Password_Hash { get; set; }
        public string Salt_Key { get; set; }
        public DateTime Locked_Time { get; set; } 
    }
}
