using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace POS.Domain.Common
{
   public class StationsClass
    {
        public string Station_ID { get; set; }
        public string Store_ID { get; set; }
        public int CSO { get; set; }
        public int DSO { get; set; }
        public int ISO { get; set; }
        public int VSO { get; set; }
        public string CDL { get; set; }
        public string PDL { get; set; }
        public int Pole_Type { get; set; }
        public string Scale_Port { get; set; }
        public string Ticket_Port { get; set; }
        public string Voucher_Port { get; set; }
        public string BCB_Port { get; set; }
        public string SCP_700_Port { get; set; }
        public string Epson_Cutter_Port { get; set; }
        public int Printer_Type { get; set; }
        public string Printer_Port { get; set; }
        public int Show_Cust_Display { get; set; }
        public int Show_Toolbar { get; set; }
        public string API { get; set; }
        public int Receipt_Format { get; set; }
        public int Deadbeat_Control { get; set; }
        public int Prompt_Amt_Tend { get; set; }
        public int Prompt_Table { get; set; }
        public int Prompt_ID { get; set; }
        public int Prompt_Salesperson { get; set; }
        public int Logo_Type { get; set; }
        public string Logo_Loc { get; set; }
        public string Order_Dest { get; set; }
        public int Stock_Prompt { get; set; }
        public int numReceiptCopies { get; set; }
        public int Dirty { get; set; }
        public int InvScreen { get; set; }
        public string FullSize_Printer { get; set; }
        public int Idle_LogOut { get; set; }
        public int CCTip { get; set; }
        public int Prompt_Zip { get; set; }
        public DateTime Last_DDR { get; set; }
        public int Use_Sig_Pad_CC { get; set; }
        public int Require_Swipe { get; set; }
        public string Receipt_Printer { get; set; }
        public string Report_Printer { get; set; }
        public string Full_Receipt_Printer { get; set; }
        public string Slip_Printer { get; set; }
        public int DispTaxInPrice { get; set; }
        public int numDocketCopies { get; set; }
        public string CC_Proc_Drive { get; set; }
        public int Check_Speed_Entry { get; set; }
        public int Prompt_Party_Size { get; set; }
        public int Order_By_Guest { get; set; }
        public string Label_Printer { get; set; }
        public string SigPadPort { get; set; }
        public int TS_Custom { get; set; }
        public int AmtTendScreen { get; set; }
        public int Def_OrderType { get; set; }
        public int Allow_End_Trans { get; set; }
        public int Prompt_Aher_Order { get; set; }
        public int PinPad_Type { get; set; }
        public string PinPad_Port { get; set; }
        public int Login_Background { get; set; }
        public int Login_Foreground { get; set; }
        public string Login_Picture { get; set; }
        public int Login_AlphaNum { get; set; }
        public int Record_CashierID { get; set; }
        public int Change_Display { get; set; }
        public int Quick_Tender { get; set; }
        public int ify_Exp_Member { get; set; }
        public int Station_Merchant { get; set; }
        public int Item_OnTheFly { get; set; }
        public int Disp_Sec_Desc { get; set; }
        public int Print_Epson_Logo { get; set; }
        public int Quick_Bar { get; set; }
        public int Use_Cash_Alerts { get; set; }
        public int Kitchen_Require_Name { get; set; }
        public int OverPayment_As_Tip { get; set; }
        public int TS_StockLevel { get; set; }
        public int BarcodeOnHold { get; set; }
        public int CD_Open { get; set; }
        public int OnHold_Use_Invoice_Number { get; set; }
        public string PicPath { get; set; }
        public int SigPadType { get; set; }
        public int AcceptSigs { get; set; }
        public int SuppressSigCopy { get; set; }
        public int MultipleMenus { get; set; }
        public int Last_Invoice_Number { get; set; }
        public int Receipt_Display_ItemCount { get; set; }
        public int AllowSwipeFromInvoice { get; set; }
        public string Scale_Port2 { get; set; }
        public string Endorse_Printer { get; set; }
        public string Fax_Printer { get; set; }
        public int Last_MoneyActivity_Index { get; set; }
        public int Last_TimeClock_Index { get; set; }
        public int Last_ExceptionIndex { get; set; }
        public string Section_ID { get; set; }
        public int TABLE_HIDE_OPENTABS { get; set; }
        public int TABLE_HIDE_TAKEOUT { get; set; }
        public int TABLE_HIDE_DELIVERY { get; set; }
        public int TABLE_HIDE_QUICKTAB { get; set; }
        public int DisableTimeBasedPricing { get; set; }
        public int PrintSuggestedTip { get; set; }
        public int ScaleWeightFormatting { get; set; }
        public int Cash_Count { get; set; }
        public int PrintDeliveryLabels { get; set; }
        public int Role { get; set; }
        public string CoinDispenserPort { get; set; }
        public string LastCreditReferenceNo { get; set; }
        public string Receipt_Printer_Logo { get; set; }
        public decimal Current_Cash { get; set; }
        public int UseIDScanner { get; set; }
        public int RecallOnHoldScreen { get; set; }
        public int CheckCashDrawerBeforeInvoice { get; set; }
        public int DVRCameraID { get; set; }
        public int QuickCash_EnterKey { get; set; }
        public int BarCodeComplete { get; set; }
        public string Label_Printer_Secondary { get; set; }
        public int PromptIdentifier { get; set; }
        public int PromptQuantityType { get; set; }
        public int PinpadConnectionType { get; set; }
        public string PinpadIPAddress { get; set; }
        public int PinpadIPPort { get; set; }
        public int Prompt_TipAmount { get; set; }
        public string OPOSMsr { get; set; }
        public int ShowInvAdjustButtonInRetail { get; set; }
        public int CommissionPrompt { get; set; }
        public int PromptEmailPurchaseOrder { get; set; }
        public decimal C2_Count { get; set; }
        public int DeliScaleType { get; set; }
        public string DeliScaleProgramPath { get; set; }
        public int ScratchBoardUpdate { get; set; }
        public int ShowCustomerInfoAlwaysInRetail { get; set; }
        public int ExternalDVRClientStatus { get; set; }
        public string ExternalDVRClientExePath { get; set; }
        public string ExternalDVRClientArgs { get; set; }
        public int HoldBarTabs { get; set; }
        public string MSRDeviceSerialNumber { get; set; }
        public int WirelessPayment { get; set; }
        public string WirelessPaymentIPPort { get; set; }
        public int EnableGasPumpInterface { get; set; }
        public int KitchenPrinter_FontSize { get; set; }
        public int Usealternatecashdrawerstatuscheck { get; set; }
        public int PinPad_MSRTrack { get; set; }
        public string Current_Key { get; set; }
        public int CustomerRequiredForDelivery { get; set; } 
    }
}
